### PR TITLE
Fix tests

### LINKED ISSUE #8: error when I ran make
Hey J,

When I ran:
`make`

A bunch of stuff was running but then I got:
`=================================== ERRORS ===========================
_______ ERROR collecting tests/timeSeries/readUnrTxyz2_test.py ______________
ImportError while importing test module '/tstools/tests/timeSeries/readUnrTxyz2_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/timeSeries/readUnrTxyz2_test.py:4: in <module>
    from timeSeries import timeSeries as ts
src/timeSeries/timeSeries.py:17: in <module>
    import plotly.graph_objects as go
E   ModuleNotFoundError: No module named 'plotly'
!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!
======================== 1 error in 0.10 seconds ===========================
make: *** [test] Error 2`

Can I fix this or is it something you should do?

### PR DESCRIPTION
**Pull request by jaredonline**
Changed a bunch of pathing, moved the `lib` directory into the `tstools.util` namespace and fixed tests.

@twistmcflip looks like the `TimeSeries.covar` attribute doesn't exist anymore. Was it replaced by something?

Fixes #8

### CODE REVIEW

**Comment by pkmcfarland** [comment]
> Changed a bunch of pathing, moved the `lib` directory into the `tstools.util` namespace and fixed tests.
> 
> @twistmcflip looks like the `TimeSeries.covar` attribute doesn't exist anymore. Was it replaced by something?

I'm pretty sure it was replaced with `TimeSeries.corr` but I have to double check. I think I initially called it covar because I thought it was storing covariances but I realized it was the correlations so I changed the attribute name.

**Comment by jaredonline** [comment]
`Timeseries.corr` passed the test [=

**Comment by pkmcfarland** [comment]
This looks great Jared. Great work!

**Review by pkmcfarland — APPROVED** [review]
Fantastic work Jared. 25% raise.

**Pull request merged**
